# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stockcontrol', '0002_auto_20171005_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='SKU',
            field=models.CharField(max_length=10, unique='true'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
